### ISSUE TITLE
βοηθέω issue

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/lsj#10]
βοηθέω link to the LSJ only gives a small piece of the total entry.

**Comment by balmas** [comment]
@monzug this change has been made in the live lexicon service files.   Please verify whenever you have a chance. Thanks!

**Comment by monzug** [comment]
this entry has not been updated.  βοάω has the same results as in LSJ/perseus. but not βοηθέω  see screenshot from LSJ/perseus
@balmas, can you confirm that it has been updated?

![Screen Shot 2020-12-11 at 6 07 12 PM](https://user-images.githubusercontent.com/41396793/101933065-f3420980-3bdb-11eb-9c56-f74de1cac6ca.png)

**Comment by monzug** [comment]
lookup for βοηθέω and go to full definition on LSJ is still missing some content:
![Screen Shot 2020-12-11 at 6 10 26 PM](https://user-images.githubusercontent.com/41396793/101933350-5af85480-3bdc-11eb-9edf-9cc7ccc484cb.png)

**Comment by balmas** [comment]
hmm that's strange. It was working yesterday. I need to see if it's a caching issue.

**Comment by balmas** [comment]
yes, it was a cache issue. I think I tested the lookup differently than it was cached. the full cache has been reset now so it should be okay.  

I see this:

![6a9903bf-17ea-43d6-940b-18432f0f70f5](https://user-images.githubusercontent.com/644870/101941202-a6e3d300-3bb5-11eb-97e5-5b0526a6dbeb.png)

**Comment by monzug** [comment]
so do I now. Thanks!
