### ISSUE TITLE
Lookups for χειρ-όω do not go to the full LSJ meaning

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/lsj#11]
It just says: 
χειρό-ω- might be due to 'contamination' with the root of ὀμόργ-νυμι.]
From A Greek-English Lexicon (Henry George Liddell, Robert Scott, Oxford, Clarendon Press, 1940)

![image](https://user-images.githubusercontent.com/10435794/97808397-48c5e680-1c2c-11eb-8315-e7bd8fcf515e.png)

**Comment by balmas** [comment]
@monzug this change has been made in the live lexicon service files.   Please verify whenever you have a chance. Thanks!

**Comment by monzug** [comment]
LSJ has been updated. see attachment
![Screen Shot 2020-12-11 at 5 00 31 PM](https://user-images.githubusercontent.com/41396793/101926481-8165c200-3bd3-11eb-8566-830ad8e33b11.png)
