### ISSUE TITLE
identify greek words in short defs

### ISSUE THREAD

**Issue by balmas** [alpheios-project/lsj#12]
From #541

we should add `<span lang="grc" data-alpheios-enabled="all"></span>` around Greek words referenced in short definitions so that they can be activated properly for lookups.

The following script will do it:

```
#!/usr/bin/perl
use strict;
use Unicode::UTF8 qw[decode_utf8 encode_utf8];

while (<>) {
  chomp;
  my ($lemma,$def,$source) = split /\|/;
  $def = decode_utf8($def);
  $def =~ s/([\p{InGreekExtended}\p{InGreekAndCoptic}]+)/<span data-alpheios-enable="all" lang="grc">\1<\/span>\2/g;
  print join "|", ($lemma,encode_utf8($def),$source);
  print "\n";
}
```

**Comment by balmas** [comment]
testable now in the latest 3.3.x qa builds

words with greek in defs enabled for lookup

τύριμνος
ὑκερός

**Comment by monzug** [comment]
tested for   ὑκερός. and it worked. however  τύριμνος  was not found in Greek resources, except in Liddell. Look up to Greek def worked
