### ISSUE TITLE
fix short defs

### ISSUE THREAD

**Issue by balmas** [alpheios-project/lsj#3]
reported by @monzug 
A few terms in the short defs file have 'Erster Bericht' as the short definition. This comes from bibliographic data during the creation of the defs file. 

τίω

οὔαδας

ταργυηνός

τρύω

ἐμπολέω

ὀφελμός

**Comment by balmas** [comment]
as I was fixing these, found some more off entries 
ὦβος|Zweiter Bericht
αὐθέντρια|Zweiter Bericht
θρεμμάτιον|Dritter Bericht
τυρίμνεια|Zweiter Bericht
τύριμνος|Zweiter Bericht
ἀδέλφιον|Zweiter Bericht
ἐκδικαιόομαι|Dritter Bericht
ἑρμάδιον|Dritter Bericht
ἡρῷσσα|Dritter Bericht
ὑκερός|Zweiter Bericht

**Comment by balmas** [comment]
And these

οὐάτιον|wd[yogh ]-t = eye.
σπάλαγμα|spalagma,= compositio et ordinatio
τετράιππον|tetraipon, = quadriga
τριμαστιγίας|trimastigia, = triverbero
χυλιστά|quinista ( = confection in dynamidia
ἀπογώνιον|w(roskopikh\ moi=ra
ἔμπλουμος|pluma) = plumatus, embroidered
κριον|crion), = vervecina
μάμερτος|Mamers, = Mavors, Mars
μέλοψ|melops, = dulcis sonus, bonus cantor

**Comment by monzug** [comment]
spring cleaning?

**Comment by balmas** [comment]
I fixed the ones I could, using Logeion (https://logeion.uchicago.edu) as a reference
Clear your cache to test.

**Comment by monzug** [comment]
Much better than what it was before.
some haven't been fixed as they have same translation as in https://logeion.uchicago.edu, such as

σπάλαγμα|spalagma,= compositio et ordinatio
τετράιππον|tetraipon, = quadriga
τριμαστιγίας|trimastigia, = triverbero
χυλιστά|quinista ( = confection in dynamidia
and
ἔμπλουμος|pluma) = plumatus, embroidered
κριον|crion), = vervecina
μάμερτος|Mamers, = Mavors, Mars
μέλοψ|melops, = dulcis sonus, bonus cantor

others have the word repeated twice, see below

![short-def-greek](https://user-images.githubusercontent.com/41396793/64863804-b6b3e680-d603-11e9-8cd7-6af0f9fba0f1.JPG)
