### ISSUE TITLE
εἶδον

### ISSUE THREAD

**Issue by vgorman1** [alpheios-project/lsj#8]
When you call up εἶδον (an irregular that is often used as the aorist of ὁράω) there is no LSJ entry linked.  Nor is there an entry in the on-line LSJ at the TLG.  Diogenes, however, finds an entry (fairly short) and there is a rather long entry in the physical LSJ under *εἴδω [with an asterisk because it never actually occurs in the Present tense].

**Comment by balmas** [comment]
fixed in the lsj index file. Verification pending deployment of updated index files.

**Comment by balmas** [comment]
@monzug this change has been made in the live lexicon service files.   Please verify whenever you have a chance. Thanks!

**Comment by monzug** [comment]
this has been updated in LSJ.
